### ISSUE TITLE
Problem with JDK10 to generate the sources on windows 10

### ISSUE THREAD

**Issue by bernardpaulus** [spring-guides/gs-producing-web-service#14]
Hello,

I cannot generate the sources with JDK10 on windows 10, running both gradlew and mvnw from the git for windows bash CLI:

    Bernard@DESKTOP MINGW64 .../gs-producing-web-service/complete (master)
    $ java -version
    java version "10.0.1" 2018-04-17
    Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
    Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
    
    Bernard@DESKTOP MINGW64 .../gs-producing-web-service/complete (master)
    $ ./gradlew --stacktrace build
    :genJaxbErrors occurred while build effective model from C:\Users\BernardPaulus\.gradle\caches\modules-2\files-2.1\org.glassfish.jaxb\jaxb-xjc\2.2.11\2356f739b56bed93101e181ea67224f3ea35dc67\jaxb-xjc-2.2.11.pom:
        'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} in org.glassfish.jaxb:jaxb-xjc:2.2.11
    Errors occurred while build effective model from C:\Users\BernardPaulus\.gradle\caches\modules-2\files-2.1\org.glassfish.jaxb\jaxb-core\2.2.11\f3208abdc61be827cf28838c3881213648807821\jaxb-core-2.2.11.pom:
        'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} in org.glassfish.jaxb:jaxb-core:2.2.11
    Errors occurred while build effective model from C:\Users\BernardPaulus\.gradle\caches\modules-2\files-2.1\org.glassfish.jaxb\txw2\2.2.11\4be03527dbf2428f7ea99fb9c2f50f089dffad5e\txw2-2.2.11.pom:
        'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} in org.glassfish.jaxb:txw2:2.2.11
    Errors occurred while build effective model from C:\Users\BernardPaulus\.gradle\caches\modules-2\files-2.1\org.glassfish.jaxb\codemodel\2.2.11\328b52a88fcab47e646af9f54580f95326557590\codemodel-2.2.11.pom:
        'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} in org.glassfish.jaxb:codemodel:2.2.11
    Errors occurred while build effective model from C:\Users\BernardPaulus\.gradle\caches\modules-2\files-2.1\com.sun.xml.bind.external\rngom\2.2.11\ffb74f1c310b0694012b56319f39c4a31ed0148b\rngom-2.2.11.pom:
        'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} in com.sun.xml.bind.external:rngom:2.2.11
    Errors occurred while build effective model from C:\Users\BernardPaulus\.gradle\caches\modules-2\files-2.1\com.sun.istack\istack-commons-tools\2.21\25ebe0fb8451bb4cb700312c62ee3fc1be2131d8\istack-commons-tools-2.21.pom:
        'dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} in com.sun.istack:istack-commons-tools:2.21
     FAILED
    
    FAILURE: Build failed with an exception.
    
    * Where:
    Build file 'C:\Users\BernardPaulus\OneDrive - Ferrologic AB\junk\java\spring\spring-ws-soap\gs-producing-web-service\complete\build.gradle' line: 35
    
    * What went wrong:
    Execution failed for task ':genJaxb'.
    > java.lang.Error: java.lang.reflect.InvocationTargetException
    
    * Try:
    Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':genJaxb'.
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
            at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
            at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
            at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
            at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
            at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
            at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
            at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
            at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
            at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
            at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
            at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
            at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
            at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
            at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
    Caused by: : java.lang.Error: java.lang.reflect.InvocationTargetException
            at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:116)
            at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:78)
            at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:103)
            at org.gradle.internal.metaobject.BeanDynamicObject$GroovyObjectAdapter.invokeOpaqueMethod(BeanDynamicObject.java:579)
            at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:506)
            at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
            at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:57)
            at build_djs527exe8jd2i11g0xd0dimg$_run_closure2$_closure7$_closure8.doCall(C:\Users\BernardPaulus\OneDrive - Ferrologic AB\junk\java\spring\spring-ws-soap\gs-producing-web-service\complete\build.gradle:35)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
            at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
            at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
            at org.gradle.api.internal.project.DefaultProject.ant(DefaultProject.java:1107)
            at org.gradle.api.Project$ant.call(Unknown Source)
            at build_djs527exe8jd2i11g0xd0dimg$_run_closure2$_closure7.doCall(C:\Users\BernardPaulus\OneDrive - Ferrologic AB\junk\java\spring\spring-ws-soap\gs-producing-web-service\complete\build.gradle:29)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:726)
            at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:699)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
            ... 30 more
    Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
            at com.sun.tools.xjc.reader.Ring.get(Ring.java:113)
            at com.sun.tools.xjc.reader.xmlschema.BGMBuilder.<init>(BGMBuilder.java:147)
            at com.sun.tools.xjc.reader.xmlschema.BGMBuilder.build(BGMBuilder.java:117)
            at com.sun.tools.xjc.ModelLoader.annotateXMLSchema(ModelLoader.java:425)
            at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:170)
            at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
            at com.sun.tools.xjc.XJC2Task._doXJC(XJC2Task.java:517)
            at com.sun.tools.xjc.XJC2Task.doXJC(XJC2Task.java:457)
            at com.sun.tools.xjc.XJC2Task.execute(XJC2Task.java:380)
            at com.sun.istack.tools.ProtectedTask.execute(ProtectedTask.java:103)
            at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            ... 58 more
    Caused by: java.lang.reflect.InvocationTargetException
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at com.sun.tools.xjc.reader.Ring.get(Ring.java:102)
            ... 72 more
    Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
            at com.sun.tools.xjc.reader.Ring.get(Ring.java:113)
            at com.sun.tools.xjc.reader.xmlschema.BindingComponent.getClassSelector(BindingComponent.java:65)
            at com.sun.tools.xjc.reader.xmlschema.ColorBinder.<init>(ColorBinder.java:62)
            at com.sun.tools.xjc.reader.xmlschema.BindGreen.<init>(BindGreen.java:63)
            ... 76 more
    Caused by: java.lang.reflect.InvocationTargetException
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at com.sun.tools.xjc.reader.Ring.get(Ring.java:102)
            ... 79 more
    Caused by: java.lang.NoClassDefFoundError: javax/activation/MimeTypeParseException
            at com.sun.tools.xjc.reader.Ring.get(Ring.java:100)
            at com.sun.tools.xjc.reader.xmlschema.DefaultClassBinder.<init>(DefaultClassBinder.java:98)
            at com.sun.tools.xjc.reader.xmlschema.ClassSelector.<init>(ClassSelector.java:214)
            ... 83 more
    Caused by: java.lang.ClassNotFoundException: javax.activation.MimeTypeParseException
            at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1386)
            at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1335)
            at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1090)
            ... 86 more
    
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 2s
    1 actionable task: 1 executed
    Bernard@DESKTOP MINGW64 .../gs-producing-web-service/complete (master)
    $ ./mvnw package
    [INFO] Scanning for projects...
    [INFO]
    [INFO] ------------------------------------------------------------------------
    [INFO] Building gs-producing-web-service 0.1.0
    [INFO] ------------------------------------------------------------------------
    [INFO]
    [INFO] --- jaxb2-maven-plugin:1.6:xjc (xjc) @ gs-producing-web-service ---
    [INFO] Generating source...
    [INFO] parsing a schema...
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 6.592 s
    [INFO] Finished at: 2018-06-21T11:00:12+02:00
    [INFO] Final Memory: 19M/77M
    [INFO] ------------------------------------------------------------------------
    ---------------------------------------------------
    constituent[0]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/aether-api-1.0.2.v20150114.jar
    constituent[1]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/aether-connector-basic-1.0.2.v20150114.jar
    constituent[2]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/aether-impl-1.0.2.v20150114.jar
    constituent[3]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/aether-spi-1.0.2.v20150114.jar
    constituent[4]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/aether-transport-wagon-1.0.2.v20150114.jar
    constituent[5]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/aether-util-1.0.2.v20150114.jar
    constituent[6]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/aopalliance-1.0.jar
    constituent[7]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/cdi-api-1.0.jar
    constituent[8]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/commons-cli-1.2.jar
    constituent[9]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/commons-io-2.2.jar
    constituent[10]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/commons-lang-2.6.jar
    constituent[11]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/commons-lang3-3.4.jar
    constituent[12]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/guava-18.0.jar
    constituent[13]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/guice-4.0-no_aop.jar
    constituent[14]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/javax.inject-1.jar
    constituent[15]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/jsoup-1.7.2.jar
    constituent[16]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/jsr250-api-1.0.jar
    constituent[17]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/maven-aether-provider-3.3.9.jar
    constituent[18]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/maven-artifact-3.3.9.jar
    constituent[19]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/maven-builder-support-3.3.9.jar
    constituent[20]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/maven-compat-3.3.9.jar
    constituent[21]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/maven-core-3.3.9.jar
    constituent[22]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/maven-embedder-3.3.9.jar
    constituent[23]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/maven-model-3.3.9.jar
    constituent[24]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/maven-model-builder-3.3.9.jar
    constituent[25]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/maven-plugin-api-3.3.9.jar
    constituent[26]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/maven-repository-metadata-3.3.9.jar
    constituent[27]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/maven-settings-3.3.9.jar
    constituent[28]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/maven-settings-builder-3.3.9.jar
    constituent[29]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/org.eclipse.sisu.inject-0.3.2.jar
    constituent[30]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/org.eclipse.sisu.plexus-0.3.2.jar
    constituent[31]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/plexus-cipher-1.7.jar
    constituent[32]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/plexus-component-annotations-1.6.jar
    constituent[33]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/plexus-interpolation-1.21.jar
    constituent[34]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/plexus-sec-dispatcher-1.3.jar
    constituent[35]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/plexus-utils-3.0.22.jar
    constituent[36]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/slf4j-api-1.7.5.jar
    constituent[37]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/slf4j-simple-1.7.5.jar
    constituent[38]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/wagon-file-2.10.jar
    constituent[39]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/wagon-http-2.10-shaded.jar
    constituent[40]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/wagon-http-shared-2.10.jar
    constituent[41]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/lib/wagon-provider-api-2.10.jar
    constituent[42]: file:/C:/Users/BernardPaulus/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/conf/logging/
    ---------------------------------------------------
    Exception in thread "main" java.lang.reflect.InvocationTargetException
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:564)
            at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
            at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
            at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
    Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
            at com.sun.tools.xjc.reader.Ring.get(Ring.java:113)
            at com.sun.tools.xjc.reader.xmlschema.BGMBuilder.<init>(BGMBuilder.java:147)
            at com.sun.tools.xjc.reader.xmlschema.BGMBuilder.build(BGMBuilder.java:117)
            at com.sun.tools.xjc.ModelLoader.annotateXMLSchema(ModelLoader.java:425)
            at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:174)
            at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
            at com.sun.tools.xjc.Driver.run(Driver.java:333)
            at org.codehaus.mojo.jaxb2.AbstractXjcMojo.execute(AbstractXjcMojo.java:316)
            at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
            at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
            at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
            at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
            at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
            at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
            at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
            at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
            at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
            at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
            at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:564)
            at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
            at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
            at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
            at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
            ... 7 more
    Caused by: java.lang.reflect.InvocationTargetException
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
            at com.sun.tools.xjc.reader.Ring.get(Ring.java:102)
            ... 36 more
    Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
            at com.sun.tools.xjc.reader.Ring.get(Ring.java:113)
            at com.sun.tools.xjc.reader.xmlschema.BindingComponent.getClassSelector(BindingComponent.java:65)
            at com.sun.tools.xjc.reader.xmlschema.ColorBinder.<init>(ColorBinder.java:62)
            at com.sun.tools.xjc.reader.xmlschema.BindGreen.<init>(BindGreen.java:63)
            ... 41 more
    Caused by: java.lang.reflect.InvocationTargetException
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
            at com.sun.tools.xjc.reader.Ring.get(Ring.java:102)
            ... 44 more
    Caused by: java.lang.NoClassDefFoundError: javax/activation/MimeTypeParseException
            at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
            at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3090)
            at java.base/java.lang.Class.getConstructor0(Class.java:3295)
            at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2512)
            at com.sun.tools.xjc.reader.Ring.get(Ring.java:100)
            at com.sun.tools.xjc.reader.xmlschema.DefaultClassBinder.<init>(DefaultClassBinder.java:98)
            at com.sun.tools.xjc.reader.xmlschema.ClassSelector.<init>(ClassSelector.java:214)
            ... 49 more
    Caused by: java.lang.ClassNotFoundException: javax.activation.MimeTypeParseException
            at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
            at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
            at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
            at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
            ... 56 more

When I change my JDK to jdk1.8.0_172, it all works.

I can't spend more time on this right now, but I thought I should report the issue :)

Kind regards,

Bernard

**Comment by bernardpaulus** [comment]
[Docs state](https://docs.spring.io/spring-ws/docs/3.0.1.RELEASE/reference/#_runtime_environment):

> Spring Web Services requires a standard Java 7 Runtime Environment. Java 8 is also supported

=> closing

**Comment by gregturn** [comment]
Thanks @bernardpaulus. We're modestly aware of Java 9+ issues and are working on how to increase support for ALL the guides in a consistent fashion.
